### PR TITLE
Add OSX ARM builds for catboost

### PR DESCRIPTION
**Pull request by giswqs**
This PR adds ARM builds for catboost by following the [conda-forge arm builds instructions](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/). It is essential that catboost has ARM builds so that downstream packages (e.g., autogluon) can support Apple M1.

Relevant issues:

- https://github.com/autogluon/autogluon/issues/612
- https://github.com/autogluon/autogluon/issues/1242

@Innixma  @gradientsky

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by giswqs** [comment]
@conda-forge-admin, please rerender

**Comment by giswqs** [comment]
Note that the OSX ARM Migrator failed. See https://github.com/conda-forge/catboost-feedstock/pull/94. We will have to fix this manually.

**Comment by giswqs** [comment]
Just updated. Let's see how it goes.

**Comment by giswqs** [comment]
@ngam The osx arm64 builds went smoothly. Thank you very much for your help!!

**Comment by giswqs** [comment]
@sab @kizill @andrey-khropov @nikitxskv @dbakshee This PR adds OSX ARM support for catboost. All checks have passed. It would be great if you can review and merge the PR so that downstream packages can support for OSX ARM as well. Thank you.

**Comment by kizill** [comment]
Thank you very much!

**Pull request merged**
